# Generated by Django 5.2.5 on 2025-08-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AddField(
            model_name='conta',
            name='data',
            field=models.DateField(default='2024-01-01', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
