# Generated by Django 5.2.5 on 2025-08-26 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_conta_options_conta_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Admin'), ('viewer', 'Visualizador')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='core.base'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['base', 'data'], name='core_conta_base_id_e8a0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['base', 'criado_em'], name='core_conta_base_id_ef7a93_idx'),
        ),
        migrations.AddField(
            model_name='membership',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.base'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='base',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='bases', through='core.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'base')},
        ),
    ]
