# Generated by Django 5.2.5 on 2025-08-28 16:40

import core.models
import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_base_membership_conta_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=512, storage=core.storages.S3PrivateMediaStorage(), upload_to=core.models.anexo_upload_to)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanho', models.BigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'base'), name='uniq_user_base'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.base'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.conta'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['base', 'conta'], name='core_anexo_base_id_6bed1d_idx'),
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['criado_em'], name='core_anexo_criado__59de17_idx'),
        ),
    ]
