# Generated by Django 5.2.5 on 2025-08-28 18:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anexo_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='logo',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=core.models.base_logo_upload_to),
        ),
    ]
