# Generated by Django 5.2.5 on 2025-08-28 19:07

import core.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_base_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='logo',
            field=models.ImageField(blank=True, max_length=512, null=True, storage=core.storages.S3PrivateMediaStorage(), upload_to=core.models.base_logo_upload_to),
        ),
    ]
