# Generated by Django 5.2.5 on 2025-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_base_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='powerbi_url',
            field=models.URLField(default=1, max_length=800, verbose_name='URL de incorporação do Power BI'),
            preserve_default=False,
        ),
    ]
