# Generated by Django 5.2.5 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
